### PR TITLE
Release/0.9.9

### PR DESCRIPTION
**Pull request by marksabbath**
Bugfix release, which resolves issues where some links were not properly redirecting.

Reported here: https://wordpress.org/support/topic/error-404-after-update-2/

### CODE REVIEW

**Comment by marksabbath** [comment]
> It looks like the Gruntfile.js was there for i18n. We do need to regenerate the .pot file since the files have been reorganized.

Hey @dreamwhisper that's true. So thinking on it, I've removed the Grunt but added the a method similar to what we're using on Genesis. You can see that [here](https://github.com/studiopress/simple-urls/pull/19/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R13)

So moving forward, to generate the .pot file, we would need to run `npm run makepot`.

**Comment by dreamwhisper** [comment]
@marksabbath gotcha, missed that as I was looking for the updated file! :) 

Not sure where in the plugin release process it should happen, but just want to make sure it gets updated.

**Comment by marksabbath** [comment]
@dreamwhisper I'm not sure either, but I think that at this point it would be a good time, so I've run `npm run makepot` and we have an updated `.pot` file now :D

@nathanrice creating the `.pot` file in this step (release branch) would be the normal/best approach?

**Comment by nathanrice** [comment]
>creating the .pot file in this step (release branch) would be the normal/best approach?

Yes, but in the future, my recommendation would be to do separate PRs for the actual fix and the release (version bump, changelog update, POT generation, etc.)

**Pull request merged**
